name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v .

    - uses: actions/upload-artifact@v4
      with:
        name: bin
        path: git-carbon

  cram:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: bin
    - name: Setup
      run: |
        chmod +x git-carbon
        python -m venv .cram-venv
        .cram-venv/bin/pip install cram
        git config --global user.name "Github Actions"
        git config --global user.email "actions@example.com"
    - name: Test
      run: |
        .cram-venv/bin/cram ./tests/
